"""empty message

Revision ID: 0a42491a703d
Revises: 
Create Date: 2021-09-22 23:06:40.674546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42491a703d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('number_of_cages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cage_number', sa.Integer(), nullable=True),
    sa.Column('Room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('species', sa.String(length=15), nullable=True),
    sa.Column('Cage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cage_id'], ['cage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    op.drop_table('cage')
    op.drop_table('room')
    op.drop_table('admin')
    # ### end Alembic commands ###
