"""empty message

Revision ID: 52a3c932e1dd
Revises: 
Create Date: 2021-10-05 20:52:05.792846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a3c932e1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('number_of_cages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cage_number', sa.Integer(), nullable=True),
    sa.Column('Room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cage_number')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('species', sa.String(length=15), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('Cage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cage_id'], ['cage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    op.drop_table('cage')
    op.drop_table('room')
    # ### end Alembic commands ###
