"""empty message

Revision ID: 7485f3a695c6
Revises: 
Create Date: 2021-09-21 21:58:38.322994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7485f3a695c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('Room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('number_of_cages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Room_id'], ['Room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('species', sa.String(length=15), nullable=True),
    sa.Column('Cage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cage_id'], ['Cage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Animal')
    op.drop_table('Cage')
    op.drop_table('Room')
    op.drop_table('Admin')
    # ### end Alembic commands ###
